/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class artech_com_arcam_NativeClass */

#ifndef _Included_artech_com_arcam_NativeClass
#define _Included_artech_com_arcam_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     artech_com_arcam_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_artech_com_arcam_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
